<?php
/**
 * Kirki config
 *
 */
?>
<?php 
function sirius_kirki_config() {
	$strings = array(
        'background-color'      => esc_attr__( 'Background Color', 'sirius-lite' ),
        'background-image'      => esc_attr__( 'Background Image', 'sirius-lite'),
        'no-repeat'             => esc_attr__( 'No Repeat', 'sirius-lite'),
        'repeat-all'            => esc_attr__( 'Repeat All', 'sirius-lite'),
        'repeat-x'              => esc_attr__( 'Repeat Horizontally', 'sirius-lite'),
        'repeat-y'              => esc_attr__( 'Repeat Vertically', 'sirius-lite'),
        'inherit'               => esc_attr__( 'Inherit', 'sirius-lite'),
        'background-repeat'     => esc_attr__( 'Background Repeat', 'sirius-lite'),
        'cover'                 => esc_attr__( 'Cover', 'sirius-lite'),
        'contain'               => esc_attr__( 'Contain', 'sirius-lite'),
        'background-size'       => esc_attr__( 'Background Size', 'sirius-lite'),
        'fixed'                 => esc_attr__( 'Fixed', 'sirius-lite'),
        'scroll'                => esc_attr__( 'Scroll', 'sirius-lite'),
        'background-attachment' => esc_attr__( 'Background Attachment', 'sirius-lite'),
        'left-top'              => esc_attr__( 'Left Top', 'sirius-lite'),
        'left-center'           => esc_attr__( 'Left Center', 'sirius-lite'),
        'left-bottom'           => esc_attr__( 'Left Bottom', 'sirius-lite'),
        'right-top'             => esc_attr__( 'Right Top', 'sirius-lite'),
        'right-center'          => esc_attr__( 'Right Center', 'sirius-lite'),
        'right-bottom'          => esc_attr__( 'Right Bottom', 'sirius-lite'),
        'center-top'            => esc_attr__( 'Center Top', 'sirius-lite'),
        'center-center'         => esc_attr__( 'Center Center', 'sirius-lite'),
        'center-bottom'         => esc_attr__( 'Center Bottom', 'sirius-lite'),
        'background-position'   => esc_attr__( 'Background Position', 'sirius-lite'),
        'background-opacity'    => esc_attr__( 'Background Opacity', 'sirius-lite'),
        'on'                    => esc_attr__( 'ON', 'sirius-lite'),
        'off'                   => esc_attr__( 'OFF', 'sirius-lite'),
        'all'                   => esc_attr__( 'All', 'sirius-lite'),
        'cyrillic'              => esc_attr__( 'Cyrillic', 'sirius-lite'),
        'cyrillic-ext'          => esc_attr__( 'Cyrillic Extended', 'sirius-lite'),
        'devanagari'            => esc_attr__( 'Devanagari', 'sirius-lite'),
        'greek'                 => esc_attr__( 'Greek', 'sirius-lite'),
        'greek-ext'             => esc_attr__( 'Greek Extended', 'sirius-lite'),
        'khmer'                 => esc_attr__( 'Khmer', 'sirius-lite'),
        'latin'                 => esc_attr__( 'Latin', 'sirius-lite'),
        'latin-ext'             => esc_attr__( 'Latin Extended', 'sirius-lite'),
        'vietnamese'            => esc_attr__( 'Vietnamese', 'sirius-lite'),
        'hebrew'                => esc_attr__( 'Hebrew', 'sirius-lite'),
        'arabic'                => esc_attr__( 'Arabic', 'sirius-lite'),
        'bengali'               => esc_attr__( 'Bengali', 'sirius-lite'),
        'gujarati'              => esc_attr__( 'Gujarati', 'sirius-lite'),
        'tamil'                 => esc_attr__( 'Tamil', 'sirius-lite'),
        'telugu'                => esc_attr__( 'Telugu', 'sirius-lite'),
        'thai'                  => esc_attr__( 'Thai', 'sirius-lite'),
        'serif'                 => _x( 'Serif', 'font style', 'sirius-lite'),
        'sans-serif'            => _x( 'Sans Serif', 'font style', 'sirius-lite'),
        'monospace'             => _x( 'Monospace', 'font style', 'sirius-lite'),
        'font-family'           => esc_attr__( 'Font Family', 'sirius-lite'),
        'font-size'             => esc_attr__( 'Font Size', 'sirius-lite'),
        'font-weight'           => esc_attr__( 'Font Weight', 'sirius-lite'),
        'line-height'           => esc_attr__( 'Line Height', 'sirius-lite'),
        'font-style'            => esc_attr__( 'Font Style', 'sirius-lite'),
        'letter-spacing'        => esc_attr__( 'Letter Spacing', 'sirius-lite'),
        'top'                   => esc_attr__( 'Top', 'sirius-lite'),
        'bottom'                => esc_attr__( 'Bottom', 'sirius-lite'),
        'left'                  => esc_attr__( 'Left', 'sirius-lite'),
        'right'                 => esc_attr__( 'Right', 'sirius-lite'),
        'color'                 => esc_attr__( 'Color', 'sirius-lite'),
        'add-image'             => esc_attr__( 'Add Image', 'sirius-lite'),
        'change-image'          => esc_attr__( 'Change Image', 'sirius-lite'),
        'remove'                => esc_attr__( 'Remove', 'sirius-lite'),
        'no-image-selected'     => esc_attr__( 'No Image Selected', 'sirius-lite'),
        'select-font-family'    => esc_attr__( 'Select a font-family', 'sirius-lite'),
        'variant'               => esc_attr__( 'Variant', 'sirius-lite'),
        'subsets'               => esc_attr__( 'Subset', 'sirius-lite'),
        'size'                  => esc_attr__( 'Size', 'sirius-lite'),
        'height'                => esc_attr__( 'Height', 'sirius-lite'),
        'spacing'               => esc_attr__( 'Spacing', 'sirius-lite'),
        'ultra-light'           => esc_attr__( 'Ultra-Light 100', 'sirius-lite'),
        'ultra-light-italic'    => esc_attr__( 'Ultra-Light 100 Italic', 'sirius-lite'),
        'light'                 => esc_attr__( 'Light 200', 'sirius-lite'),
        'light-italic'          => esc_attr__( 'Light 200 Italic', 'sirius-lite'),
        'book'                  => esc_attr__( 'Book 300', 'sirius-lite'),
        'book-italic'           => esc_attr__( 'Book 300 Italic', 'sirius-lite'),
        'regular'               => esc_attr__( 'Normal 400', 'sirius-lite'),
        'italic'                => esc_attr__( 'Normal 400 Italic', 'sirius-lite'),
        'medium'                => esc_attr__( 'Medium 500', 'sirius-lite'),
        'medium-italic'         => esc_attr__( 'Medium 500 Italic', 'sirius-lite'),
        'semi-bold'             => esc_attr__( 'Semi-Bold 600', 'sirius-lite'),
        'semi-bold-italic'      => esc_attr__( 'Semi-Bold 600 Italic', 'sirius-lite'),
        'bold'                  => esc_attr__( 'Bold 700', 'sirius-lite'),
        'bold-italic'           => esc_attr__( 'Bold 700 Italic', 'sirius-lite'),
        'extra-bold'            => esc_attr__( 'Extra-Bold 800', 'sirius-lite'),
        'extra-bold-italic'     => esc_attr__( 'Extra-Bold 800 Italic', 'sirius-lite'),
        'ultra-bold'            => esc_attr__( 'Ultra-Bold 900', 'sirius-lite'),
        'ultra-bold-italic'     => esc_attr__( 'Ultra-Bold 900 Italic', 'sirius-lite'),
        'invalid-value'         => esc_attr__( 'Invalid Value', 'sirius-lite'),
    
    );	

	$args = array(
        //'logo_image'     => get_template_directory_uri() . '/customize/images/logo.jpg',
        'url_path'       => get_stylesheet_directory_uri() . '/inc/kirki/',
        'textdomain'     => 'sirius-lite',
        'i18n'           => $strings,		
        'disable_loader' => true
    );
	return $args;
}
add_filter( 'kirki/config', 'sirius_kirki_config' );
?>